# Generated by Django 4.2.4 on 2023-09-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_hitter_batting_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='comments',
            field=models.CharField(max_length=255),
        ),
    ]
