# Generated by Django 4.2.4 on 2023-09-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_hitter_fielding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitter',
            name='field_position',
            field=models.CharField(choices=[('C', 'C'), ('1B', '1B'), ('2B', '2B'), ('3B', '3B'), ('SS', 'SS'), ('OF', 'OF'), ('DH', 'DH')], max_length=10),
        ),
    ]
