# Generated by Django 4.2.4 on 2023-09-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitter',
            name='batting_position',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('S', 'Switch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hitter',
            name='field_position',
            field=models.CharField(choices=[('C', 'Catcher'), ('1B', 'First Baseman'), ('2B', 'Second Baseman'), ('3B', 'Third Baseman'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter')], max_length=10),
        ),
    ]
