# Generated by Django 4.2.4 on 2023-09-08 00:53

from django.db import migrations

def populate_teams(apps, schema_editor):
    Team = apps.get_model("player", "Team")
    TEAMS = [
        ("ari", "Arizona Diamondbacks"),
        ("atl", "Atlanta Braves"),
        ("bal", "Baltimore Orioles"),
        ("bos", "Boston Red Sox"),
        ("chc", "Chicago Cubs"),
        ("cws", "Chicago White Sox"),
        ("cin", "Cincinnati Reds"),
        ("cle", "Cleveland Guardians"),
        ("col", "Colorado Rockies"),
        ("det", "Detroit Tigers"),
        ("hou", "Houston Astros"),
        ("kc", "Kansas City Royals"),
        ("laa", "Los Angeles Angels"),
        ("lad", "Los Angeles Dodgers"),
        ("mia", "Miami Marlins"),
        ("mil", "Milwaukee Brewers"),
        ("min", "Minnesota Twins"),
        ("nym", "New York Mets"),
        ("nyy", "New York Yankees"),
        ("oak", "Oakland Athletics"),
        ("phi", "Philadelphia Phillies"),
        ("pit", "Pittsburgh Pirates"),
        ("sd", "San Diego Padres"),
        ("sf", "San Francisco Giants"),
        ("sea", "Seattle Mariners"),
        ("stl", "St. Louis Cardinals"),
        ("tb", "Tampa Bay Rays"),
        ("tex", "Texas Rangers"),
        ("tor", "Toronto Blue Jays"),
        ("was", "Washington Nationals"),
    ]

    for code, name in TEAMS:
        Team.objects.create(code=code, name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_team_alter_category_slug_pitcher_pitch_hitter'),
    ]

    operations = [
        migrations.RunPython(populate_teams),
    ]
